"""Private, crash-resistant control files and project exchange snapshots."""

from __future__ import annotations

import contextlib
import fcntl
import hashlib
import json
import os
from pathlib import Path
import uuid

PRIVATE_DIR_MODE = 0o700
PRIVATE_FILE_MODE = 0o600
MAX_INPUT_BYTES = 1_048_576
PROJECT_DIR = ".subagent-bridge"
EXCHANGE_DIR = "exchange"


def ensure_private_dir(path: Path | str) -> Path:
    path = Path(path)
    if path.is_symlink():
        raise ValueError(f"refusing symlinked directory: {path}")
    path.mkdir(parents=True, exist_ok=True, mode=PRIVATE_DIR_MODE)
    if path.is_symlink() or not path.is_dir():
        raise ValueError(f"not a directory: {path}")
    if os.stat(path, follow_symlinks=False).st_uid == os.geteuid():
        os.chmod(path, PRIVATE_DIR_MODE)
    return path


def fsync_dir(path: Path | str) -> None:
    try:
        descriptor = os.open(str(path), os.O_RDONLY)
    except OSError:
        return
    try:
        os.fsync(descriptor)
    except OSError:
        pass
    finally:
        os.close(descriptor)


def atomic_write_bytes(path: Path | str, data: bytes) -> Path:
    path = Path(path)
    ensure_private_dir(path.parent)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.{uuid.uuid4().hex}.tmp")
    try:
        descriptor = os.open(
            temporary,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
            PRIVATE_FILE_MODE,
        )
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        os.chmod(path, PRIVATE_FILE_MODE, follow_symlinks=False)
        fsync_dir(path.parent)
        return path
    finally:
        with contextlib.suppress(FileNotFoundError):
            temporary.unlink()


def atomic_write_json(path: Path | str, value: object) -> Path:
    data = (json.dumps(value, ensure_ascii=False, indent=2) + "\n").encode()
    return atomic_write_bytes(path, data)


def discover_workspace_root(start: Path | str) -> Path:
    path = Path(start).expanduser().resolve()
    if path.is_file():
        path = path.parent
    if not path.is_dir():
        raise ValueError(f"workspace is not a directory: {path}")
    for candidate in (path, *path.parents):
        marker = candidate / ".git"
        if marker.is_dir() or marker.is_file():
            return candidate
    return path


def ensure_project_exchange(workspace: Path | str) -> Path:
    root = discover_workspace_root(workspace)
    project_state = ensure_private_dir(root / PROJECT_DIR)
    ignore = project_state / ".gitignore"
    if ignore.is_symlink() or (ignore.exists() and not ignore.is_file()):
        raise ValueError(f"invalid project ignore file: {ignore}")
    existing = ignore.read_text(encoding="utf-8") if ignore.exists() else ""
    rules = [
        line.strip()
        for line in existing.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    if not rules or rules[-1] not in {"*", "**"}:
        prefix = existing + ("\n" if existing and not existing.endswith("\n") else "")
        atomic_write_bytes(
            ignore,
            (prefix + "# Generated by subagent-bridge; local exchange only.\n*\n").encode(),
        )
    return ensure_private_dir(project_state / EXCHANGE_DIR)


def attempt_exchange_dir(
    workspace: Path | str, task_id: str, attempt_id: str
) -> Path:
    base = ensure_project_exchange(workspace)
    return ensure_private_dir(base / task_id / "attempts" / attempt_id)


def _bounded_regular_file(path: Path, role: str) -> bytes:
    if path.is_symlink() or not path.is_file():
        raise ValueError(f"{role} must be a regular non-symlink file: {path}")
    with path.open("rb") as handle:
        data = handle.read(MAX_INPUT_BYTES + 1)
    if not data:
        raise ValueError(f"{role} must not be empty: {path}")
    if len(data) > MAX_INPUT_BYTES:
        raise ValueError(f"{role} exceeds {MAX_INPUT_BYTES} bytes: {path}")
    return data


def context_version(task_data: bytes, context_data: bytes | None) -> str:
    digest = hashlib.sha256(b"subagent-bridge-context-v1\0")
    for label, data in ((b"task", task_data), (b"context", context_data)):
        if data is None:
            continue
        digest.update(label + b"\0" + str(len(data)).encode() + b"\0" + data)
    return "v1-" + digest.hexdigest()[:12]


def snapshot_inputs(
    exchange_attempt: Path | str,
    task_file: Path | str,
    context_file: Path | str | None = None,
) -> dict[str, object]:
    attempt = ensure_private_dir(exchange_attempt)
    inputs = ensure_private_dir(attempt / "inputs")
    task_data = _bounded_regular_file(Path(task_file), "task")
    context_data = (
        _bounded_regular_file(Path(context_file), "context")
        if context_file is not None
        else None
    )
    lock_path = attempt / ".snapshot.lock"
    descriptor = os.open(
        lock_path,
        os.O_RDWR | os.O_CREAT | getattr(os, "O_NOFOLLOW", 0),
        PRIVATE_FILE_MODE,
    )
    try:
        with os.fdopen(descriptor, "a+b") as lock:
            fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
            for name, data in (("task.md", task_data), ("context.md", context_data)):
                if data is None:
                    continue
                destination = inputs / name
                if destination.exists():
                    if destination.is_symlink() or destination.read_bytes() != data:
                        raise FileExistsError(f"refusing to replace snapshot: {destination}")
                else:
                    atomic_write_bytes(destination, data)
    except Exception:
        # fdopen owns descriptor after successful construction.
        raise
    version = context_version(task_data, context_data)
    return {
        "schema_version": 1,
        "context_version": version,
        "task_path": str(inputs / "task.md"),
        "task_sha256": hashlib.sha256(task_data).hexdigest(),
        "task_bytes": len(task_data),
        "context_path": str(inputs / "context.md") if context_data is not None else None,
        "context_sha256": hashlib.sha256(context_data).hexdigest() if context_data else None,
        "context_bytes": len(context_data) if context_data is not None else None,
    }

